<template>
  <svg
    viewBox="0 0 240 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    role="img"
    aria-label="iFlow Lite"
  >
    <rect
      x="4"
      y="6"
      width="36"
      height="36"
      rx="10"
      fill="currentColor"
      opacity="0.1"
    />
    <path
      d="M16 17H28M16 31H28M16 17V31M28 17L23 24L28 31"
      stroke="currentColor"
      stroke-width="2.4"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
    <circle
      cx="16"
      cy="17"
      r="3.5"
      fill="var(--ui-primary)"
    />
    <circle
      cx="23"
      cy="24"
      r="3.5"
      fill="currentColor"
    />
    <circle
      cx="16"
      cy="31"
      r="3.5"
      fill="var(--ui-primary)"
    />
    <text
      x="52"
      y="25"
      fill="currentColor"
      font-size="22"
      font-family="'Avenir Next', 'Segoe UI', sans-serif"
      font-weight="700"
      letter-spacing="0.3"
      dominant-baseline="middle"
    >
      iFlow
    </text>
    <text
      x="114"
      y="25"
      fill="var(--ui-primary)"
      font-size="22"
      font-family="'Avenir Next', 'Segoe UI', sans-serif"
      font-weight="600"
      letter-spacing="0.2"
      dominant-baseline="middle"
    >
      Lite
    </text>
  </svg>
</template>
